
#本项目端口号
server:
  port: 8903

#服务的名称
spring:
  application:
    name: service-config
  #git 地址
  cloud:
    config:
      server:
        git:
          uri: https://github.com/chengyangyang/config.git
          search-paths: springcloud


#http请求地址和资源文件映射如下:
#{application}/{profile}[/{label}]
#{application}-{profile}.yml
#{label}/{application}-{profile}.yml
#{application}-{profile}.properties
#{label}/{application}-{profile}.properties









