
#本项目端口号
server:
  port: 8903

#服务的名称
spring:
  application:
    name: service-config
  #git 地址
  cloud:
    config:
      server:
        git:
          uri: https://github.com/chengyangyang/config.git
          search-paths: springcloud

#添加注册中心(进行注册)
eureka:
  instance: localhost
  client:
    service-url:
     defaultZone: http://localhost:8901/eureka/
    register-with-eureka: true
    fetch-registry: false


#http请求地址和资源文件映射如下:
#{application}/{profile}[/{label}]
#{application}-{profile}.yml
#{label}/{application}-{profile}.yml
#{application}-{profile}.properties
#{label}/{application}-{profile}.properties


#配置文件在本地
#spring.profiles.active=native
#配置文件的目录
#spring.cloud.config.server.native.search-locations=D:/workspace/GitHub/spring-config/config-f
#或者spring.cloud.config.server.native.search-locations=classpath:/config






